
-- GENEROS
INSERT INTO GENEROS (ID, NOMBRE, DESCRIPCION, ESTADO, FECHA_CREACION) VALUES (1, 'Ficción', 'Novelas y relatos de ficción literaria', 1, CURRENT_TIMESTAMP);
INSERT INTO GENEROS (ID, NOMBRE, DESCRIPCION, ESTADO, FECHA_CREACION) VALUES (2, 'Ciencia Ficción', 'Obras basadas en especulaciones científicas', 1, CURRENT_TIMESTAMP);
INSERT INTO GENEROS (ID, NOMBRE, DESCRIPCION, ESTADO, FECHA_CREACION) VALUES (3, 'Fantasía', 'Narrativa fantástica con elementos mágicos', 1, CURRENT_TIMESTAMP);
INSERT INTO GENEROS (ID, NOMBRE, DESCRIPCION, ESTADO, FECHA_CREACION) VALUES (4, 'Historia', 'Libros sobre eventos y procesos históricos', 1, CURRENT_TIMESTAMP);
INSERT INTO GENEROS (ID, NOMBRE, DESCRIPCION, ESTADO, FECHA_CREACION) VALUES (5, 'Tecnología', 'Programación y arquitectura de software', 1, CURRENT_TIMESTAMP);
INSERT INTO GENEROS (ID, NOMBRE, DESCRIPCION, ESTADO, FECHA_CREACION) VALUES (6, 'Filosofía', 'Pensamiento crítico y tratados filosóficos', 1, CURRENT_TIMESTAMP);

-- LIBROS
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (1, 'Cien Años de Soledad', 'Gabriel García Márquez', '9780307474728', 5, 45.00, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (2, 'Don Quijote de la Mancha', 'Miguel de Cervantes', '9788424115814', 3, 50.00, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (3, 'Pedro Páramo', 'Juan Rulfo', '9788437604183', 4, 35.00, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (4, 'La Ciudad y los Perros', 'Mario Vargas Llosa', '9788420471839', 6, 40.00, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (5, 'Fahrenheit 451', 'Ray Bradbury', '9780307347978', 4, 38.00, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (6, 'Un Mundo Feliz', 'Aldous Huxley', '9788497594257', 5, 42.00, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (7, 'Dune', 'Frank Herbert', '9780441172719', 8, 60.00, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (8, 'Neuromante', 'William Gibson', '9788445074244', 3, 37.00, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (9, 'El Señor de los Anillos', 'J.R.R. Tolkien', '9788445071793', 10, 85.00, 1, 3, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (10, 'El Hobbit', 'J.R.R. Tolkien', '9788445073841', 7, 45.00, 1, 3, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (11, 'Juego de Tronos', 'George R.R. Martin', '9788496208964', 6, 70.00, 1, 3, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (12, 'El Nombre del Viento', 'Patrick Rothfuss', '9788401337208', 4, 55.00, 1, 3, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (13, 'Sapiens: De animales a dioses', 'Yuval Noah Harari', '9788499926223', 5, 65.00, 1, 4, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (14, 'Guns, Germs, and Steel', 'Jared Diamond', '9780393317558', 3, 50.00, 1, 4, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (15, 'Historia de dos Ciudades', 'Charles Dickens', '9788491050803', 2, 30.00, 1, 4, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (16, 'Clean Code', 'Robert C. Martin', '9780132350884', 6, 90.00, 1, 5, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (17, 'Design Patterns', 'Erich Gamma et al.', '9780201633610', 4, 95.00, 1, 5, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (18, 'Spring Boot in Action', 'Craig Walls', '9781617292545', 3, 80.00, 1, 5, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (19, 'Así habló Zaratustra', 'Friedrich Nietzsche', '9788420633190', 3, 35.00, 1, 6, CURRENT_TIMESTAMP);
INSERT INTO LIBROS (ID, TITULO, AUTOR, ISBN, STOCK, COSTO_REPOSICION, ESTADO, GENERO_ID, FECHA_CREACION) VALUES (20, 'Meditaciones', 'Marco Aurelio', '9788424938444', 5, 28.00, 1, 6, CURRENT_TIMESTAMP);

-- SOCIOS
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (1, 'Juan', 'Pérez', '45871234', 'juan.perez@email.com', '987654321', 'Av. Lima 123', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (2, 'Maria', 'Gómez', '48963215', 'maria.gomez@email.com', '912345678', 'Calle Arequipa 456', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (3, 'Carlos', 'López', '41236589', 'carlos.lopez@email.com', '955443322', 'Jr. Cusco 789', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (4, 'Ana', 'Torres', '47852369', 'ana.torres@email.com', '966554433', 'Av. Sol 321', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (5, 'Luis', 'Mendoza', '43215987', 'luis.mendoza@email.com', '977665544', 'Calle Grau 654', 0, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (6, 'Sofia', 'Ramírez', '49871236', 'sofia.ramirez@email.com', '988776655', 'Av. Larco 987', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (7, 'Diego', 'Fernández', '46582139', 'diego.fernandez@email.com', '999887766', 'Jr. Union 147', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (8, 'Elena', 'Sánchez', '42369851', 'elena.sanchez@email.com', '911223344', 'Av. Brasil 258', 1, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (9, 'Jorge', 'Castro', '41472583', 'jorge.castro@email.com', '922334455', 'Calle Real 369', 0, CURRENT_TIMESTAMP);
INSERT INTO SOCIOS (ID, NOMBRES, APELLIDOS, DNI, EMAIL, TELEFONO, DIRECCION, ESTADO, FECHA_CREACION) VALUES (10, 'Patricia', 'Flores', '48521369', 'patricia.flores@email.com', '933445566', 'Av. Marina 741', 1, CURRENT_TIMESTAMP);

-- PRESTAMOS
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (1, 1, CURRENT_TIMESTAMP, DATE '2026-01-24', DATE '2026-01-20', 45.00, 'DEVUELTO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (2, 2, CURRENT_TIMESTAMP, DATE '2026-01-26', DATE '2026-01-25', 38.00, 'DEVUELTO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (3, 3, CURRENT_TIMESTAMP, DATE '2026-01-29', DATE '2026-01-28', 85.00, 'DEVUELTO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (4, 4, CURRENT_TIMESTAMP, DATE '2026-02-15', DATE '2026-02-14', 65.00, 'DEVUELTO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (5, 6, CURRENT_TIMESTAMP, DATE '2026-02-19', DATE '2026-02-18', 90.00, 'DEVUELTO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (6, 1, CURRENT_TIMESTAMP, DATE '2026-09-24', NULL, 50.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (7, 2, CURRENT_TIMESTAMP, DATE '2026-09-26', NULL, 42.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (8, 3, CURRENT_TIMESTAMP, DATE '2026-09-28', NULL, 60.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (9, 4, CURRENT_TIMESTAMP, DATE '2026-09-29', NULL, 45.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (10, 7, CURRENT_TIMESTAMP, DATE '2026-09-30', NULL, 70.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (11, 5, CURRENT_TIMESTAMP, DATE '2026-08-15', NULL, 40.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (12, 8, CURRENT_TIMESTAMP, DATE '2026-08-19', NULL, 55.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (13, 10, CURRENT_TIMESTAMP, DATE '2026-08-24', NULL, 95.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (14, 6, CURRENT_TIMESTAMP, DATE '2026-08-26', NULL, 80.00, 'REGISTRADO');
INSERT INTO PRESTAMOS (ID, SOCIO_ID, FECHA, FECHA_DEVOLUCION_PREVISTA, FECHA_DEVOLUCION_REAL, TOTAL_VALORIZADO, ESTADO) VALUES (15, 7, CURRENT_TIMESTAMP, DATE '2026-08-29', NULL, 28.00, 'REGISTRADO');

-- 6. INSERTAR DETALLE_PRESTAMOS
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (1, 1, 1, 1, 45.00, 45.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (2, 2, 5, 1, 38.00, 38.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (3, 3, 9, 1, 85.00, 85.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (4, 4, 13, 1, 65.00, 65.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (5, 5, 16, 1, 90.00, 90.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (6, 6, 2, 1, 50.00, 50.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (7, 7, 6, 1, 42.00, 42.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (8, 8, 7, 1, 60.00, 60.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (9, 9, 10, 1, 45.00, 45.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (10, 10, 11, 1, 70.00, 70.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (11, 11, 4, 1, 40.00, 40.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (12, 12, 12, 1, 55.00, 55.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (13, 13, 17, 1, 95.00, 95.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (14, 14, 18, 1, 80.00, 80.00);
INSERT INTO DETALLE_PRESTAMOS (ID, PRESTAMO_ID, LIBRO_ID, CANTIDAD, COSTO_UNITARIO, SUBTOTAL) VALUES (15, 15, 20, 1, 28.00, 28.00);

COMMIT;